name: 'Build URL PR Comment for React App'
description: 'Add a Build URL comment to new pull requests for React App.'
author: 'Ayush Dabhi'
branding:
  icon: 'git-pull-request'
  color: 'blue'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  github-event-path:
    description: 'Path to the GitHub event file'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.github-event-path }}
