name: 'Build url PR Comment for React App'
description: 'Add a Build URL comment to new pull requests for React App.'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}

branding:
  icon: 'award'
  color: 'green'

